### PR TITLE
Added --https option in sdss_install_bootstrap

### PR DESCRIPTION
**Pull request by nbmurphy**
I added --https option in sdss_install_bootstrap. This was a missing piece to pull request #47.

### CODE REVIEW

**Comment by nbmurphy** [comment]
I just tested this on my machine. Since it's such a small change, I'm going to go ahead and merge to master, delete tag 1.0.6 and re-tag.

**Review by joelbrownstein — APPROVED** [review]
looks good

**Comment by joelbrownstein** [comment]
ok, but make new tag 1.0.7 (and don't delete 1.0.6, please)

**Comment by nbmurphy** [comment]
I apologize @joelbrownstein, I didn’t see your message before I deleted and re-tagged sdss_install 1.0.6. I Just successfully ran `sdss_install_bootstrap` using the tag 1.0.6. Everything works as expected.

**Pull request merged**
