### PR TITLE
Allow installing external dependencies as modules

### LINKED ISSUE #1: Make idlutils sdss_install'able

### LINKED ISSUE #39: Allow installing external dependencies as modules
Based on the conversation around [idlutils](https://github.com/sdss/idlutils) we need a new feature to be able to install external (non SDSS, non sdss_install-enabled) dependencies. For the particular case of idlutils we need that when we sdss_install it, the Coyote and Goddard IDL libraries be downloaded and installed as modules.

I think the right place for defining this would be the config.ini in idlutils. We would need to add a new section (or something in the `sds4install` section) to define the name of the external library, its GitHub repository URL, and the tag to checkout (or master). Maybe something like

```
[sdss4install]
evilmake = True
no_python_package = True
external_dependencies = 
	coyote = https://github.com/idl-coyote/coyote, master
	goddard = https://github.com/wlandsman/IDLAstro, 1.0.1
```

### PR DESCRIPTION
**Pull request by nbmurphy**
Closes #39 and closes sdss/idlutils#1

### CODE REVIEW

**Comment by nbmurphy** [comment]
This is getting very close. I should probably add some code for external dependencies cloned from SVN. @joelbrownstein and @albireox do you know of a use case for this?

I decided to make an `[external_dependencies]` section in the `ini` file of sdss/idlutils. 
I would like to propose the following JSON standard for the `keys` in this section:
```
{
 "install_product": {
   "url": "product_url",
   "version": "product_version"
  },
 "paths": {
  "idl": ["idl_dir0","idl_dirN"],
  "shell": ["shell_dir0","shell_dirN"],
  "python": ["python_dir0","python_dirN"]
 }
}
```
`product_url` is of the form `https://github.com/product_owner/product_name`, `git@github.com:product_owner/product_name`, or `https://svn.sdss.org/product_owner/product_name`, and  `idl_dirN`, `bin_dirN`, and `python_dirN` are subdirectories with respect to the product's git repository root directory.

**Comment by nbmurphy** [comment]
@joelbrownstein and @albireox I've decided to exclude SVN external dependencies from Issue #39 until I have a use case to test code changes against; the associated method currently just prints an error message encouraging the user to create a sdss_install issue when such a use case arises. Everything else seems to be working correctly (see below).

I'm requesting that this pull request be merged to master.

```
[ben@cypher:sdss]$ sdss_install -v idlutils external_dependencies -G -F
sdss_install - INFO - Install5.py - line 90 - Validating product
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --heads git@github.com:sdss/idlutils.git master
sdss_install - DEBUG - Install5.py - line 99 - Valid product: idlutils
sdss_install - INFO - Install5.py - line 110 - Validating version
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --heads git@github.com:sdss/idlutils.git external_dependencies
sdss_install - DEBUG - Install5.py - line 123 - Valid version: external_dependencies
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --heads git@github.com:sdss/idlutils.git external_dependencies
sdss_install - INFO - Install.py - line 252 - Preparing to install in /Users/ben/software/sdss/github/idlutils/external_dependencies (overwriting due to force option)
sdss_install - DEBUG - Install5.py - line 303 - Running command: git clone git@github.com:sdss/idlutils.git /Users/ben/software/sdss/idlutils-external_dependencies
sdss_install - INFO - Install5.py - line 309 - Completed GitHub clone of repository idlutils
sdss_install - DEBUG - Install5.py - line 358 - Running command: git checkout external_dependencies
sdss_install - INFO - Install5.py - line 364 - Completed checkout of branch external_dependencies
sdss_install - INFO - Install.py - line 647 - Installing via evilmake
sdss_install - INFO - modules.py - line 81 - module load dust (dependency)
sdss_install - INFO - modules.py - line 81 - module load photolog (dependency)
sdss_install - INFO - modules.py - line 81 - module load twomass (dependency)
sdss_install - INFO - modules.py - line 81 - module load usno (dependency)
sdss_install - INFO - modules.py - line 81 - module load goddard (dependency)
sdss_install - INFO - modules.py - line 81 - module load coyote (dependency)
sdss_install - INFO - modules.py - line 200 - Adding module file /Users/ben/software/sdss/github/modulefiles/idlutils/external_dependencies
sdss_install - INFO - Install5.py - line 90 - Validating product
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --heads https://github.com/idl-coyote/coyote.git master
sdss_install - DEBUG - Install5.py - line 99 - Valid product: coyote
sdss_install - INFO - Install5.py - line 110 - Validating version
sdss_install - DEBUG - Install5.py - line 123 - Valid version: master
sdss_install - INFO - Install.py - line 252 - Preparing to install in /Users/ben/software/sdss/github/external/coyote (overwriting due to force option)
sdss_install - DEBUG - Install5.py - line 303 - Running command: git clone https://github.com/idl-coyote/coyote /Users/ben/software/sdss/github/external/coyote/master
sdss_install - INFO - Install5.py - line 309 - Completed GitHub clone of repository coyote
sdss_install - DEBUG - Install5.py - line 325 - Skipping checkout for master branch
sdss_install - INFO - Install.py - line 491 - Loading current IDL_PATH
sdss_install - INFO - Install.py - line 500 - Updated IDL_PATH
sdss_install - DEBUG - Install.py - line 503 - environ['IDL_PATH']: /Users/ben/software/sdss/github/external/coyote/master:+/Users/ben/software/sdss/github/idlutils/external_dependencies/goddard/pro:+/Users/ben/software/sdss/github/idlutils/external_dependencies/pro
sdss_install - INFO - Install5.py - line 90 - Validating product
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --heads https://github.com/wlandsman/IDLAstro.git master
sdss_install - DEBUG - Install5.py - line 99 - Valid product: IDLAstro
sdss_install - INFO - Install5.py - line 110 - Validating version
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --heads https://github.com/wlandsman/IDLAstro.git 1.0.1
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --tags https://github.com/wlandsman/IDLAstro.git 1.0.1
sdss_install - DEBUG - Install5.py - line 123 - Valid version: 1.0.1
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --heads https://github.com/wlandsman/IDLAstro.git 1.0.1
sdss_install - DEBUG - Install5.py - line 250 - Running command: git ls-remote --tags https://github.com/wlandsman/IDLAstro.git 1.0.1
sdss_install - INFO - Install.py - line 252 - Preparing to install in /Users/ben/software/sdss/github/external/IDLAstro (overwriting due to force option)
sdss_install - DEBUG - Install5.py - line 303 - Running command: git clone https://github.com/wlandsman/IDLAstro /Users/ben/software/sdss/github/external/IDLAstro/1.0.1
sdss_install - INFO - Install5.py - line 309 - Completed GitHub clone of repository IDLAstro
sdss_install - DEBUG - Install5.py - line 358 - Running command: git checkout tags/1.0.1
sdss_install - INFO - Install5.py - line 364 - Completed checkout of tag tags/1.0.1 and removal of .git directory
sdss_install - INFO - Install.py - line 491 - Loading current IDL_PATH
sdss_install - INFO - Install.py - line 500 - Updated IDL_PATH
sdss_install - DEBUG - Install.py - line 503 - environ['IDL_PATH']: /Users/ben/software/sdss/github/external/IDLAstro/1.0.1/pro:/Users/ben/software/sdss/github/external/coyote/master:+/Users/ben/software/sdss/github/idlutils/external_dependencies/goddard/pro:+/Users/ben/software/sdss/github/idlutils/external_dependencies/pro
sdss_install - INFO - Install.py - line 691 - Installing in /Users/ben/software/sdss/github/idlutils/external_dependencies
sdss_install - INFO - modules.py - line 81 - module load idlutils/external_dependencies (dependency)
sdss_install - INFO - Install.py - line 701 - Running "evilmake clean" in /Users/ben/software/sdss/github/idlutils/external_dependencies
sdss_install - DEBUG - Install.py - line 703 - OS type detected: Darwin
...
...
...
```

**Review by albireox — APPROVED** [review]
Looks good!

**Comment by nbmurphy** [comment]
Per the request of @albireox  if the `etc/config.ini` file of an installed product has an `external_dependencies` section, `sdss_install` now expects only one option `json_filepath` which points to a JSON file, `etc/config.json` for example, that contains information regarding external dependencies. All the changes seem to work correctly.

I'm requesting that this pull request be merged with master.

**Pull request merged**
